<?php
/**
 * @var \ArtGalerie\AgCategory\Block\AllKuenstler $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager

$categories = getSubCategories(29);
$abc = array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','R','Q','S','T','U','V','W','X','Y','Z','*');
$letters = array();
$artists = array();
foreach($categories as $category){ 
	$object_manager = $objectManager->create('Magento\Catalog\Model\Category')->load($category->getId());
	$category = $object_manager->getName();
    if(!in_array($category[0], $letters)){
    	$letters[$category[0]] = $category[0];
    }
}
$letters_array = $letters;
foreach($letters as $l){
	foreach($categories as $cat){
		$object_manager = $objectManager->create('Magento\Catalog\Model\Category')->load($cat->getId());
        if($object_manager->getImageUrl()){
            $category_image = $object_manager->getImageUrl();
        } else {
          	$category_image = 'http://ag.avidel.de/pub/media/catalog/arts.jpg';
        }
	    $category_name = $cat->getName();
	    $artists[$category_name]['url'] = $object_manager->getUrl();
	    $artists[$category_name]['name'] = $category_name;
	    $artists[$category_name]['category_image'] = $category_image;
	}
}
?>
<div class="container" style="margin-top: 200px;">
	<div class="row">
		<ul class="breadcrumb">
		  <li><a href="/">All Themen</a></li>
		  <li><a href="#">Kuenstler</a></li>
		</ul>
		<p>Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs</p>
		<div class="col-lg-4 com-md-4 col-sm-4 col-xs-12">
			<div class="panel-block-row">
				<div class="ag__promo-banner--wrapper ag__promo-banner-m promobanner zoom">
                    <a href="#">
						<img class="img-responsive"
							src="http://ag.avidel.de/pub/media/catalog/product/u/w/uwe-steger-platzhirsch_wg_ig_4500.jpg" alt=""
							data-src="http://ag.avidel.de/pub/media/catalog/product/u/w/uwe-steger-platzhirsch_wg_ig_4500.jpg">
					</a>
					<div class="ag__promo-banner ag__promo-banner--atomic-tangerine">
						<h3>Static Elemen 1</h3>
						<h5 class="sub-title ">Uwe Steger, Platzhirsch...</h5>
						<a class="btn btn-default btn-transparent" href="#">Unsere Bestseller</a>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-4 com-md-4 col-sm-4 col-xs-12">
			<div class="panel-block-row">
				<div class="ag__promo-banner--wrapper ag__promo-banner-m promobanner zoom">
                    <a href="#">
						<img class="img-responsive"
							src="http://ag.avidel.de/pub/media/wysiwyg/slider/Rectangle%205.png" alt=""
							data-src="http://ag.avidel.de/pub/media/wysiwyg/slider/Rectangle%205.png">
					</a>
					<div class="ag__promo-banner ag__promo-banner--bitter-lemon">
						<h3>Static Elemen 2</h3>
						<h5 class="sub-title ">Edward Hooper, Portait of...</h5>
						<a class="btn btn-default btn-transparent" href="#">Zu den Angeboten</a>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-4 com-md-4 col-sm-4 col-xs-12">
			<div class="panel-block-row">
				<div class="ag__promo-banner--wrapper ag__promo-banner-m promobanner zoom">
                    <a href="#">
						<img class="img-responsive"
							src="http://ag.avidel.de/pub/media/wysiwyg/slider/Rectangle%206.png" alt=""
							data-src="http://ag.avidel.de/pub/media/wysiwyg/slider/Rectangle%206.png">
					</a>
					<div class="ag__promo-banner ag__promo-banner--atomic-tangerine">
						<h3>Static Elemen 3</h3>
						<h5 class="sub-title ">33% auf alle Acrylglasbilder</h5>
						<a class="btn btn-default btn-transparent" href="#">Zur Themenwelt</a>
					</div>
				</div>
			</div>
		</div>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<?php sort($letters_array);  foreach($letters_array as $l){ ?>
             <a href="#<?php echo $l; ?>" class="abc"><?php echo $l; ?></a>
			<?php } ?>
		</div>
		<?php 
            sort($letters);
            sort($artists);
		?>
		<?php foreach($letters as $l): ?>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 abc-container">
			<a href="#" id="<?php echo $l ?>" class="pull-left abc"><?php echo $l; ?></a><a href="#" class="pull-right abc">Show All</a>
		</div>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<div class="owl-carousel owl-theme">
				<?php foreach($artists as $a){ 
					  $name = $a['name'];
                      if($l == $name[0]){
				?>
			    <div class="item">
			    	<div class="panel-block-row">
						<div class="ag__promo-banner--wrapper ag__artist-lists promobanner zoom">
		                    <img src="<?php echo $a['category_image']; ?>">
		                    <a href="<?php echo $a['url']; ?>"><span><?php echo $name; ?></span></a>
						</div>
					</div>
			    </div>
			    <?php } }?>
			</div>
		</div>
        <?php endforeach; ?>
	</div>
</div>

<script type="text/javascript">
	require([
		'jquery',
		'mgs/owlcarousel'
	], function ($) {
        $('.owl-carousel').owlCarousel({
		    loop:true,
		    margin:10,
		    nav:true,
		    dots: false,
		    nav: false,
		    responsive:{
		        0:{
		            items:1
		        },
		        600:{
		            items:3
		        },
		        1000:{
		            items:4
		        }
		    }
		});
	});
</script>